### ISSUE TITLE
Fix improper use of CString

### ISSUE THREAD

**Issue by mcwissink** [scholtzan/rust-fluidsynth#2]
According to the Rust docs: [https://doc.rust-lang.org/1.15.1/std/ffi/struct.CString.html#method.as_ptr](url)
The current use of CString causes the new CString to be deallocated immediately after allocation.

fluid_synth_sfload and other functions don't receive the intended CString, causing things to not work as expected.

**Comment by mcwissink** [comment]
This has already been fixed

**Comment by scholtzan** [comment]
Sorry, it has been a while since I actually worked on this repo. I merged the proposed changes just now in case you are still interested in using it.
