### ISSUE TITLE
Maybe change the license to MIT?

### ISSUE THREAD

**Issue by chengchangwu** [scholtzan/rust-fluidsynth#4]
Although the license of fluidsynth is LGPL，this binding need not to be LGPL。If this binding is LGPL，then one cannot statically link his application to it without releasing the source of his application. If the binding is in MIT, one can statically link his application to the binding, then dynamically link to libfluidsynth, without releasing his source.

**Comment by scholtzan** [comment]
Right. I changed it to MIT.
